### ISSUE TITLE
When do you plan to release the code

### ISSUE THREAD

**Issue by leocnj** [A2Zadeh/MFN#1]
Hi Amir,

In your MRN repo, I saw that you mentioned that MRN code will be released under your CMU SDK shortly. Will the MFN code be treated in a similar way?  Thanks.

**Comment by impredicative** [comment]
That was in March. What a scam. The paper says:

> All the code and data required to recreate the reported results are available at https://github.com/A2Zadeh/MFN

I wonder how many more lies exist in the paper. You make a superlative claim:

> MFN outperforms all the existing multi-view approaches. Furthermore, MFN outperforms all current state-of-the-art models, setting new state-of-the-art results for these multi-view datasets. 

But you've no code and models to back up your claim. Bogus paper.

**Comment by A2Zadeh** [comment]
Hello @impredicative,

The reason for us not being able to release the code is that the original version is in Theano, which is now deprecated. We have been struggling to rewrite the code in pytorch, mainly because we are very busy with new ideas and algorithms so we are a bit stretched thin. 

When writing a paper, it is reasonable to expect that you as the person who wants to publish will reimplement your baselines. For example, many of the baselines in this paper were recreated by us and not provided any code.

**Comment by impredicative** [comment]
> The reason for us not being able to release the code is that the original version is in Theano, which is now deprecated. We have been struggling to rewrite the code in pytorch, mainly because we are very busy with new ideas and algorithms so we are a bit stretched thin.

> When writing a paper, it is reasonable to expect that you as the person who wants to publish will reimplement your baselines. For example, many of the baselines in this paper were recreated by us and not provided any code.

The difference is that you promised something you didn't deliver on. I hope you still can, but if you stretch yourself too thin, you never will.

**Comment by A2Zadeh** [comment]
@impredicative releasing the code is still very much my intent. In the meantime, some other of our baselines which achieve even better results are released: https://github.com/Justin1904/Low-rank-Multimodal-Fusion 

I do apologize for the inconvenience this has caused. I will release the code in Theano soon, however much help it will be. For the pytorch versions, you will have to wait since we don't have them currently implemented. 

Again, thank you for your interest in the MFN. Please check CMU Multimodal SDK in the meantime.

**Comment by A2Zadeh** [comment]
@saxenarohit ,@impredicative, @leocnj, @jbschiratti 

I really and sincerely apologize for the inconvenience that this has caused. Again, to demonstrate, our code was originally in theano which was discontinued shortly after the MFN paper. On our side, we have been really busy with new research ideas and maintaining the CMU Multimodal SDK. I haven't had the time to maintain the repository for MARN and MFN, as much as I really loved to do it. 

I just sent emails to everyone involved and we WILL get this to you in the next few days one way or another, even if we have to release a semi-clean version of the theano code. The results on the paper are direct outputs of the code in theano. I will also personally write a pytorch version of the code and release it to all of you. 

Hope this helps.

**Comment by A2Zadeh** [comment]
@saxenarohit ,@leocnj, @jbschiratti 

@pliang279 just released the pytorch code for MFN. The results are consistent with our theano implementations and the paper. We also released CMU-MOSI pre-trained models. Please feel welcome to use and send us requests and questions. 

@impredicative, reimplementing the papers you read is up to YOU! This is how machine learning works. I constantly implement other people's methods and I am thankful for their explorations. I don't expect them to share their code. Providing code is an act of courtesy commonly done by researchers. A quick look at your github activity and I realized you have insulted good researchers from around the US with nonsense requests and conjectures. This is unacceptable. You need to grow up and learn that scientists don't get to high levels of research if their work is not genuine and honest. I hope you can reach out to them and apologize for your inappropriate behavior.

**Comment by axzfkdpmrzrheue** [comment]
@A2Zadeh No one is here for your religious sermon, so save it. It's not a courtesy if you already commit to something; it is when you don't. Deleting user comments and attempting to enforce your reality doesn't make it true. Let's stick to the facts that we see here, and avoid stalking users which is what you seem to be doing.
